# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 507bfb705df5d4b9429d1a1aeaeabf61b2f46266f052e8a9c0fbca3403d3711547d3508bfde4e87e4104fbefbc57c5af6fa15467f44272d879878812130a8922

test:
  secret_key_base: a926be6487b36dcbb65c544b9952ab24c52dc630aa5ca58052d1ee72848add19f5ba4fdad23d7ffb5768fbc6234dbab808b8735165601e8eeb925f302c035e72

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
